# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Winfo_Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Winfo_Swift
  pod 'SkyFloatingLabelTextField'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'EZLoadingActivity'
  pod 'SideMenu'
  pod 'SwiftMessages'

end
